import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
EMBEDDING_MODEL = "intfloat/multilingual-e5-small"
FAISS_PATH = "indexes/vector_index_combined.faiss"
BM25_PATH = "indexes/bm25_index.pkl"

FALLBACK_VIDEOS = [
    {"title": "Radha Naam Track 1", "video_url": "https://youtu.be/b43mQ1EUWKk?si=KuIYbibuOIEkaRRu", "timestamp": "00:00"},
    {"title": "Radha Naam Track 2", "video_url": "https://youtu.be/k5XZSPD4VR0?si=n5gp67Bk2K2rI0kl", "timestamp": "00:00"},
    {"title": "Radha Naam Track 3", "video_url": "https://youtu.be/VnbCqbZQzzI?si=xNvViFIpNCJyHxFI", "timestamp": "00:00"},
    {"title": "Radha Naam Track 4", "video_url": "https://youtu.be/cPa2vVmHt20?si=nMEAyrZjokeJd7TF", "timestamp": "00:00"},
    {"title": "Radha Naam Track 5", "video_url": "https://youtu.be/LWHLmMd1Uvk?si=zHAasRaiyoH27JN-", "timestamp": "00:00"},
]

OFF_TOPIC_KEYWORDS = [
    # ----- Cooking & Food -----
    "maggie", "pasta", "noodles", "sauce", "bake", "fry", "boil", "steam", "roast", "grill",
    "pizza", "burger", "sandwich", "bread", "cake", "biscuit", "curry", "rice", "dal", "sabzi",
    "chai", "tea", "coffee", "juice", "shake", "smoothie", "drink", "beverage", "cold drink", "soda",
    "jalebi", "samosa", "gulab jamun", "kheer", "halwa", "pakora", "biryani", "tikka", "masala", "chole",
    "bhature", "naan", "roti", "paratha", "lassi", "sweet", "snack", "food", "eat", "taste", "yummy",
    "momos", "dumplings", "soup", "salad", "breakfast", "lunch", "dinner", "meal", "recipe",
    "cook", "cooking", "kitchen", "stove", "oven", "microwave", "ingredient", "spice", "salt", "sugar",
    "oil", "ghee", "butter", "cheese", "yogurt", "paneer", "chicken", "mutton", "fish", "egg", "vegetable",
    "fruit", "apple", "banana", "mango", "grape", "watermelon", "cucumber", "tomato", "potato", "onion",
    "garlic", "ginger", "chilli", "pepper", "cinnamon", "cardamom", "clove", "turmeric", "cumin", "coriander", "malu", "badtameez", "gaali", "ganda", 
    "behuda", "faltu", "timepass", "bakwas", "tatti", "pota",
    
    # ----- Sports -----
    "cricket", "football", "soccer", "tennis", "basketball", "hockey", "volleyball", "baseball", "softball",
    "rugby", "golf", "badminton", "table tennis", "squash", "handball", "water polo", "swimming", "diving",
    "surfing", "skating", "skiing", "snowboarding", "cycling", "mountain biking", "triathlon", "marathon",
    "running", "jogging", "hiking", "trekking", "climbing", "rock climbing", "mountaineering", "paragliding",
    "sky diving", "bungee jumping", "kayaking", "canoeing", "rafting", "rowing", "sailing", "windsurfing",
    "kite surfing", "jet skiing", "scuba diving", "snorkeling", "fishing", "angling", "hunting", "shooting",
    "archery", "boxing", "wrestling", "mma", "ufc", "karate", "taekwondo", "judo", "kung fu", "muay thai",
    "kickboxing", "fencing", "gymnastics", "horse riding", "equestrian", "polo", "lacrosse", "netball",
    "kabaddi", "kho kho", "gilli danda", "kancha", "marbles", "chess", "carrom", "snooker", "billiards",
    "pool", "darts", "bowling", "curling", "croquet",
    
    # ----- Gaming -----
    "game", "gaming", "video game", "pc game", "console game", "handheld game", "arcade game",
    "playstation", "xbox", "nintendo", "switch", "ps4", "ps5", "xbox series", "nintendo switch", "nintendo 3ds",
    "nintendo ds", "gameboy", "gameboy advance", "nintendo 64", "gamecube", "wii", "wii u", "dreamcast",
    "sega genesis", "sega saturn", "sega dreamcast", "atari", "commodore 64", "amiga", "spectrum", "pc engine",
    "turbo grafx", "neo geo", "3do", "jaguar", "lynx", "game gear", "virtual boy", "ouya", "steam deck",
    "rog ally", "ayaneo", "gpd win", "gaming laptop", "gaming desktop", "gaming monitor", "gaming keyboard",
    "gaming mouse", "gaming headset", "gaming chair", "controller", "gamepad", "joystick", "fight stick",
    "racing wheel", "pedals", "shifter", "handbrake", "flight stick", "throttle", "rudder pedals", "vr headset",
    "oculus", "meta quest", "htc vive", "valve index", "windows mixed reality", "playstation vr", "psvr",
    "pubg", "fortnite", "apex legends", "call of duty", "warzone", "valorant", "csgo", "counter strike",
    "league of legends", "dota 2", "smite", "heroes of the storm", "overwatch", "team fortress 2",
    "rainbow six siege", "battlefield", "battlefront", "halo", "gears of war", "destiny", "borderlands",
    "far cry", "assassin's creed", "watch dogs", "the division", "ghost recon", "splinter cell", "tom clancy",
    "metal gear solid", "hitman", "dishonored", "prey", "doom", "quake", "wolfenstein", "rage", "fallout",
    "elder scrolls", "skyrim", "oblivion", "morrowind", "starfield", "avowed", "fable", "perfect dark",
    "banjo kazooie", "conker", "battletoads", "killer instinct", "crackdown", "sunset overdrive", "quantum break",
    "alan wake", "control", "max payne", "death stranding", "horizon zero dawn", "god of war", "uncharted",
    "last of us", "spider man", "ratchet and clank", "jack and daxter", "sly cooper", "infamous",
    "ghost of tsushima", "bloodborne", "demon's souls", "dark souls", "elden ring", "sekiro", "armored core",
    "final fantasy", "kingdom hearts", "dragon quest", "chrono trigger", "chrono cross", "xenogears",
    "xenosaga", "xenoblade", "tales of", "star ocean", "valkyrie profile",
    
    # ----- Entertainment -----
    "hollywood", "tollywood", "kollywood", "sandalwood", "actor", "actress", "director", "producer",
    "screenwriter", "cinematographer", "editor", "composer", "singer", "dancer", "stuntman", "vfx", "cgi",
    "animation", "documentary", "short film", "feature film", "tv series", "web series", "episode", "season",
    "sitcom", "drama", "thriller", "horror", "comedy", "romance", "action", "adventure", "sci fi", "fantasy",
    "biopic", "musical", "anime", "manga", "cartoon", "reality tv", "game show", "talk show", "news",
    "soap opera", "telenovela", "music", "song", "album", "single", "ep", "lp", "mixtape", "playlist",
    "soundtrack", "score", "rap", "hip hop", "rock", "metal", "pop", "jazz", "blues", "classical", "folk",
    "country", "electronic", "dance", "house", "techno", "trance", "dubstep", "drum and bass", "hardstyle",
    "industrial", "synthpop", "new wave", "post punk", "gothic rock", "darkwave", "dream pop", "shoegaze",
    "noise rock", "math rock", "post rock", "progressive rock", "art rock", "psychedelic rock", "garage rock",
    "indie rock", "alternative rock", "grunge", "britpop", "power pop", "power metal", "symphonic metal",
    "progressive metal", "death metal", "black metal", "doom metal", "stoner metal", "sludge metal",
    "grindcore", "metalcore", "deathcore", "djent", "nu metal", "rap metal", "crossover thrash", "thrash metal",
    "speed metal", "heavy metal", "glam metal", "industrial metal", "gothic metal", "folk metal",
    
    # ----- Technology (specific gadgets) -----
    "smartphone", "iphone", "samsung", "xiaomi", "oneplus", "google pixel", "huawei", "oppo", "vivo", "realme",
    "motorola", "nokia", "sony", "lg", "htc", "blackberry", "windows phone", "smartwatch", "fitness tracker",
    "apple watch", "galaxy watch", "fitbit", "garmin", "airpods", "earbuds", "headphones", "speakers",
    "bluetooth speaker", "soundbar", "home theater", "smart tv", "led tv", "lcd tv", "plasma tv", "oled tv",
    "projector", "monitor", "display", "touch screen", "vr headset", "ar glasses", "graphics card", "gpu", "cpu",
    "processor", "intel", "amd", "ryzen", "ram", "rom", "storage", "ssd", "hdd", "nvme", "external drive", "usb",
    "pendrive", "memory card", "sd card", "hard disk", "motherboard", "keyboard", "mouse", "mouse pad", "webcam",
    "microphone", "headset", "joystick", "gamepad", "steering wheel", "printer", "scanner", "photocopier",
    "fax machine", "3d printer", "router", "modem", "switch", "hub", "access point", "ethernet cable", "wifi",
    "bluetooth", "nfc", "rfid", "gps", "4g", "5g", "lte", "broadband", "dsl", "fiber internet", "satellite internet",
    "vpn", "proxy", "firewall", "antivirus", "malware", "spyware", "ransomware", "trojan", "worm", "virus",
    "hacking", "cracking", "phishing", "spoofing", "ddos", "software", "application", "app", "mobile app", "web app",
    "desktop app", "saas", "paas", "iaas", "cloud computing", "aws", "azure", "gcp", "docker", "kubernetes",
    "jenkins", "git", "github", "gitlab", "bitbucket", "jira", "confluence", "slack", "teams", "zoom", "skype",
    "whatsapp", "telegram", "signal", "discord", "wechat", "line", "viber", "imo", "google meet", "facetime",
    "webex", "code", "programming", "coding", "development", "devops", "backend", "frontend", "database", "sql",
    "mysql", "postgresql", "mongodb", "cassandra", "redis", "elasticsearch", "graphql", "rest api", "soap", "json",
    "xml", "html", "css", "javascript", "typescript", "python", "java", "csharp", "cplusplus", "c", "ruby", "php",
    "swift", "kotlin", "go", "rust", "scala", "perl", "haskell", "lua", "r", "matlab", "dart", "flutter", "react",
    "angular", "vue", "svelte", "jquery", "bootstrap", "tailwind", "django", "flask", "fastapi", "spring boot",
    "asp.net", "express", "nestjs", "laravel", "rails", "symfony", "codeigniter", "cakephp",
]

SPIRITUAL_KEYWORDS = [
    "krodh", "gussa", "bhakti", "premanand", "ahankar", "sadhana", "dhyaan",
    "karma", "moksha", "guru", "seva", "shanti", "prem", "satsang", "ram",
    "krishna", "radha", "bhagwan", "puja", "mantra", "yoga", "dhyan",
    "chesta", "drishti", "kam", "bhagwat", "pati", "husband", "wife", "patni",
    "divorce", "talaq", "separate", "vivah", "marriage", "relationship",
    "सहनशीलता", "भक्ति", "क्रोध", "प्रेम", "राम", "गुरु", "सेवा", "मोक्ष",
    "abuse", "abusive", "betrayal", "betray", "cheat", "cheating", "trust", "faithful",
    "child", "children", "parenting", "rape", "murder", "theft", "lie", "truth", "sin", "virtue",
    "birth", "death", "happiness", "sorrow", "patience", "jealousy", "greed", "attachment",
    "anger", "angry", "control", "problem", "stress", "anxiety", "depression", "fear", "worry",
    "loneliness", "addiction", "alcohol", "drug", "gambling", "violence", "aggression",
    "forgiveness", "compassion", "kindness", "honesty", "integrity", "loyalty", "respect",
    "gratitude", "prayer", "meditation", "devotion", "worship", "temple", "pilgrimage",
    "fasting", "surrender", "liberation", "enlightenment", "self realization", "soul", "spirit",
    "homosexual", "gay", "lesbian", "transgender", "lgbt", "समलैंगिक", "समलैंगिकता",
    "homo sexual", "homo sexuals","daughter", "father", "mother", "son", "parent", "parents", "family", "sibling", "brother", "sister",
    "beti", "pita", "maa", "baap", "bachcha", "bachchi", "rishta", "sambandh", "relationship","shree", "shri", "ji", "maharaj", "maharaja", "guru", "guruji", "swami", "sant", "bhagwan",
    "prabhu", "ishwar", "paramatma", "radhe", "radha", "krishna", "ram", "sita", "hanuman",
    "shiva", "shiv", "durga", "lakshmi", "saraswati", "ganesh", "kartikeya", "brahma",
    "vishnu", "narayan", "hari", "govind", "gopala", "nanda", "yasoda", "vrindavan", "vraj",
    "bhajan", "kirtan", "aarti", "puja", "prasad", "temple", "ashram", "satsang", "pravachan",
    "updesh", "sharan", "samarpan", "bhakti", "prem", "anand", "moksha", "mukti", "nirvana",
    "karma", "dharma", "sadhana", "dhyan", "yoga", "mantra", "japa", "tapa", "vrat", "teerth",
    # Honorifics and common spiritual titles
    "pujya", "param pujya", "paramhansa", "mahant", "acharya", "rishi", "muni", "sanyasi",
    "bhakt", "bhaktin", "sevak", "sevika", "shishya", "chela", "gurubhai", "sadhak",
]

SYNONYMS = {
    'krodh': ['gussa', 'gusa', 'anger', 'क्रोध', 'गुस्सा', 'क्रोधित', 'angry'],
    'gussa': ['krodh', 'gusa', 'anger', 'क्रोध', 'गुस्सा'],
    "bhakti": ["devotion", "भक्ति", "premanand", "prem", "bhagwan", "सेवा", "devotional"],
    "premanand": ["prem", "anand", "premanand ji", "हित प्रेमानंद"],
    "ahankar": ["ego", "अहंकार", "ahamkara", "aham", "pride"],
    "sadhana": ["practice", "साधना", "sadhan", "अभ्यास", "spiritual practice"],
    "dhyaan": ["meditation", "ध्यान", "dhyan", "ध्यान करना", "meditate"],
    "karma": ["action", "कर्म", "karm", "करम", "deed"],
    "moksha": ["liberation", "मोक्ष", "mukti", "मुक्ति", "freedom"],
    "guru": ["teacher", "गुरु", "master", "संत", "saint"],
    "seva": ["service", "सेवा", "serve", "सेवा करना", "helping"],
    "shanti": ["peace", "शांति", "shant", "शांत", "peaceful"],
    "prem": ["love", "प्रेम", "pyar", "प्यार", "loving"],
    "satsang": ["company", "सत्संग", "satsangh", "संगति", "gathering"],
    "bhagwat": ["spiritual", "भागवत", "bhagavatik", "भागवतिक", "divine"],
    "chesta": ["effort", "चेष्टा", "endeavour", "प्रयास", "attempt"],
    "drishti": ["vision", "दृष्टि", "sight", "नजर", "perspective"],
    "kam": ["lust", "काम", "desire", "वासना", "passion"],
    "ram": ["lord ram", "राम", "ram ji", "श्री राम", "rama"],
    "krishna": ["krsna", "कृष्ण", "kanha", "govind", "lord krishna"],
    "radha": ["radhika", "राधा", "radhe", "radha rani"],
    "sahanshilta": ["patience", "सहनशीलता", "tolerance", "धैर्य", "forbearance"],
    "jiyana": ["live", "जीना", "जीवन", "life", "living"],
    "pati": ["husband", "पति", "spouse", "husband"],
    "husband": ["pati", "पति", "spouse", "husband"],
    "wife": ["patni", "पत्नी", "spouse", "wife"],
    "divorce": ["talaq", "separate", "breakup", "विवाह विच्छेद", "तलाक", "अलग होना"],
    "talaq": ["divorce", "separate", "विवाह विच्छेद", "तलाक"],
    "marriage": ["vivah", "विवाह", "wedding", "shaadi", "शादी"],
    "relationship": ["sambandh", "संबंध", "relation", "rishta"],
    "problem": ["samasya", "समस्या", "issue", "trouble", "परेशानी"],
    "anger": ["krodh", "gussa", "क्रोध", "गुस्सा", "angry"],
    "control": ["niyantran", "नियंत्रण", "kam karna", "कम करना", "manage"],
    "gusa": ["gussa", "krodh", "anger"],
    "man": ["mann", "mind", "bhatakta"],
    "shadi": ["vivah", "marriage", "shaadi"],
    "abuse": ["शोषण", "abus", "abusive", "violence", "हिंसा"],
    "betrayal": ["विश्वासघात", "dhokha", "धोखा", "cheat", "betray"],
    "cheat": ["धोखा", "dhokha", "betray", "विश्वासघात", "cheating"],
    "trust": ["विश्वास", "bharosa", "भरोसा", "faith"],
    "child": ["बच्चा", "baccha", "children", "kids", "बाल"],
    "homosexual": ["समलैंगिक", "gay", "lesbian", "lgbt", "queer", "समलैंगिकता"],
    "rape": ["बलात्कार", "balatkar", "assault"],
    "murder": ["हत्या", "hatya", "killing"],
    "suicide": ["आत्महत्या", "atma hatya", "self harm"],
    "addiction": ["लत", "lat", "vyasan", "व्यसन"],
    "fear": ["डर", "dar", "bhay", "भय"],
    "anxiety": ["चिंता", "chinta", "tension", "तनाव"],
    "depression": ["अवसाद", "avasad", "udasi", "उदासी"],
    "stress": ["तनाव", "tanav", "pressure"],
    "forgiveness": ["क्षमा", "kshama", "maafi", "माफी"],
    "compassion": ["करुणा", "karuna", "daya", "दया"],
    "gratitude": ["आभार", "abhar", "kritagyata", "कृतज्ञता"],
    "prayer": ["प्रार्थना", "prarthana", "puja", "पूजा"],
    "meditation": ["ध्यान", "dhyan", "dhyaan"],
    "devotion": ["भक्ति", "bhakti", "prem", "प्रेम"],
    "surrender": ["समर्पण", "samarpan", "sharanagati", "शरणागति"],
    "liberation": ["मोक्ष", "moksha", "mukti", "मुक्ति"],
    "enlightenment": ["आत्मज्ञान", "atmagyan", "bodh", "बोध"],
    "soul": ["आत्मा", "atma", "rooh", "रूह"],
    "spirit": ["आत्मा", "atma", "chaitanya", "चैतन्य"],
    "god": ["भगवान", "bhagwan", "ishwar", "ईश्वर", "parmatma", "परमात्मा"],
    "krishna": ["krsna", "कृष्ण", "kanha", "govind", "lord krishna"],
    "radha": ["radhika", "राधा", "radhe", "radha rani"],
    "ram": ["rama", "राम", "ram ji", "shri ram"],
    "shiva": ["shiv", "शिव", "mahadev", "भोलेनाथ"],
    "durga": ["durga maa", "दुर्गा", "ambey", "अम्बे"],
    "ganesh": ["ganpati", "गणेश", "vinayak", "विनायक"],
    "hanuman": ["bajrang bali", "हनुमान", "maruti", "मारुति"],
    "sai": ["sai baba", "साई", "shirdi sai"],
    "homo sexual": ["homosexual", "gay", "lesbian", "समलैंगिक"],
    "homo sexuals": ["homosexual", "gay", "lesbian", "समलैंगिक"],
}

QUERY_EXPANSIONS = {
    "krodh": ["krodh", "krodha", "kroddh", "krod", "kroh", "gussa", "gusa", "guss", "gussa", "anger", "angry", "krodd", "kroth", "क्रोध", "गुस्सा", "क्रोधित"],
    "gussa": ["gussa", "gusa", "guss", "gussa aana", "anger", "krodh", "krod", "angry", "गुस्सा", "क्रोध"],
    "gusa": ["gussa", "krodh", "anger"],
    "man": ["mann", "mind", "bhatakta"],
    "shadi": ["vivah", "marriage", "shaadi"],
    "bhakti": ["bhakti", "bhakthi", "bhakti marg", "devotion", "devotional", "prem", "seva", "premanand", "भक्ति", "प्रेम", "सेवा"],
    "premanand": ["premanand", "premanand ji", "prem anand", "hit premanand", "shri hit premanand", "premanandji", "premananda", "प्रेमानंद", "हित प्रेमानंद"],
    "dhyaan": ["dhyaan", "dhyan", "dhyana", "dhyan", "dhyaan karna", "meditation", "meditate", "ध्यान", "ध्यान करना"],
    "ahankar": ["ahankar", "ahamkar", "ahankara", "ahamkara", "ego", "pride", "अहंकार", "अहम्"],
    "sadhana": ["sadhana", "sadhan", "sadhna", "spiritual practice", "practice", "अभ्यास", "साधना"],
    "moksha": ["moksha", "moksh", "mukti", "liberation", "freedom", "मोक्ष", "मुक्ति"],
    "guru": ["guru", "guruji", "teacher", "master", "saint", "गुरु", "संत"],
    "seva": ["seva", "sewa", "service", "serve", "helping", "सेवा", "सेवा करना"],
    "shanti": ["shanti", "shanthi", "peace", "peaceful", "शांति", "शांत"],
    "prem": ["prem", "prema", "love", "loving", "प्रेम", "प्यार"],
    "satsang": ["satsang", "satsangh", "sat sang", "spiritual gathering", "company", "सत्संग", "संगति"],
    "bhagwat": ["bhagwat", "bhagavat", "bhagavatik", "spiritual", "divine", "भागवत", "भागवतिक"],
    "chesta": ["chesta", "chesta", "effort", "endeavour", "attempt", "प्रयास", "चेष्टा"],
    "drishti": ["drishti", "dristi", "vision", "sight", "perspective", "दृष्टि", "नजर"],
    "kam": ["kam", "kaam", "lust", "desire", "passion", "काम", "वासना"],
    "ram": ["ram", "rama", "lord ram", "ram ji", "shri ram", "राम", "श्री राम"],
    "krishna": ["krishna", "krsna", "kanha", "govind", "lord krishna", "कृष्ण", "कान्हा"],
    "radha": ["radha", "radhika", "radhe", "radha rani", "राधा", "राधिका"],
    "sahanshilta": ["sahanshilta", "sahanshilta", "patience", "tolerance", "forbearance", "धैर्य", "सहनशीलता"],
    "jiyana": ["jiyana", "jiyana", "live", "life", "living", "जीना", "जीवन"],
    "pati": ["pati", "husband", "spouse", "पति", "हसबैंड"],
    "husband": ["husband", "pati", "spouse", "हसबैंड", "पति"],
    "wife": ["wife", "patni", "spouse", "पत्नी", "वाइफ"],
    "divorce": ["divorce", "talaq", "separate", "breakup", "विवाह विच्छेद", "तलाक", "अलग होना"],
    "talaq": ["talaq", "divorce", "separate", "तलाक", "विवाह विच्छेद"],
    "marriage": ["marriage", "vivah", "wedding", "shaadi", "विवाह", "शादी"],
    "relationship": ["relationship", "sambandh", "relation", "rishta", "संबंध", "रिश्ता"],
    "problem": ["problem", "samasya", "issue", "trouble", "समस्या", "परेशानी"],
    "control": ["control", "niyantran", "kam karna", "manage", "नियंत्रण", "कम करना"],
    "nij mantra": ["nij mantra", "nij", "mantra", "initiatory mantra", "personal mantra", "निज मंत्र", "upanyana mantra"],
    "sarnagat mantra": ["sarnagat mantra", "saranagat mantra", "surrender mantra", "शरणागत मंत्र"],
    "kaise": ["kaise", "kase", "kaise kare", "how to", "kese", "kaise karen"],
    "kya": ["kya", "kya hai", "what is", "kya hota hai"],
    "kyu": ["kyu", "kyun", "why", "kion"],
    "kab": ["kab", "kabhi", "when", "kab hota hai"],
    "radha rani": ["radha rani", "radha", "radhika", "radhe", "radha ji"],
    "krishna bhakti": ["krishna bhakti", "krishna devotion", "kanha bhakti", "govind bhakti"],
    "ram bhakti": ["ram bhakti", "ram devotion", "ram ji bhakti"],
    "shiv bhakti": ["shiv bhakti", "shiva devotion", "mahadev bhakti"],
    "durga bhakti": ["durga bhakti", "durga devotion", "ma durga bhakti"],
    "ganesh bhakti": ["ganesh bhakti", "ganesha devotion", "ganpati bhakti"],
    "sai bhakti": ["sai bhakti", "sai devotion", "shirdi sai bhakti"],
    "hanuman bhakti": ["hanuman bhakti", "hanuman devotion", "bajrang bali bhakti"],
    "pati patni ke jhagde": ["pati patni ke jhagde", "husband wife fights", "marital problems", "relationship issues"],
    "bachche ki problem": ["bachche ki problem", "child problem", "children issues", "parenting"],
    "maa baap ke saath vyavhar": ["maa baap ke saath vyavhar", "parents relationship", "respect parents", "parents se vyavhar"],
    "paisa ki problem": ["paisa ki problem", "money problems", "financial issues", "dhani ka upay"],
    "naukri ki problem": ["naukri ki problem", "job problems", "career issues", "employment"],
    "health problem": ["health problem", "swasthya samasya", "bimari ka upay", "health issues"],
    "stress": ["stress", "tension", "man ki tension", "mental stress", "tension kaise kam kare"],
    "anxiety": ["anxiety", "chinta", "worry", "fear", "dar", "bhay"],
    "depression": ["depression", "avasad", "udasi", "sadness", "grief", "dukh"],
    "bhagwan ka darshan": ["bhagwan ka darshan", "god vision", "darshan kaise paye", "bhagwan milna"],
    "bhagwan ki kripa": ["bhagwan ki kripa", "god's grace", "kripa kaise paye"],
    "bhagwan ki bhakti": ["bhagwan ki bhakti", "god devotion", "bhakti marg"],
    "bhagwan ka smaran": ["bhagwan ka smaran", "god remembrance", "nam jap", "japa"],
    "mantra jap": ["mantra jap", "japa", "nam jap", "mantra repetition"],
    "kirtan": ["kirtan", "bhajan", "devotional singing", "sankirtan"],
    "aarti": ["aarti", "arti", "devotional song", "puja aarti"],
    "puja vidhi": ["puja vidhi", "how to do puja", "worship method", "puja kaise kare"],
    "vrat": ["vrat", "fasting", "upvas", "vrata"],
    "tirth yatra": ["tirth yatra", "pilgrimage", "holy travel", "teerth"],
    "atm gyata": ["atm gyata", "self realization", "atman", "self knowledge", "aatma gyan"],
    "brahman": ["brahman", "brahma", "ultimate reality", "parmatma"],
    "maya": ["maya", "illusion", "moh", "attachment", "moh maya"],
    "sansar": ["sansar", "world", "material world", "samsara"],
    "punya paap": ["punya paap", "virtue sin", "good deeds bad deeds", "karma phal"],
    "janam mrityu": ["janam mrityu", "birth death", "reincarnation", "punarjanam"],
    "karma siddhant": ["karma siddhant", "law of karma", "karma theory"],
    "bhagavad gita": ["bhagavad gita", "gita", "geeta", "bhagwat geeta"],
    "ramayan": ["ramayan", "ramayana", "ram charit manas"],
    "mahabharat": ["mahabharat", "mahabharata"],
    "puran": ["puran", "purana", "hindu scriptures"],
    "ved": ["ved", "veda", "vedas"],
    "upanishad": ["upanishad", "upanishads", "vedanta"],
    "bhakti marg": ["bhakti marg", "bhakti maarg", "devotion path", "bhakti yoga"],
    "gyan marg": ["gyan marg", "knowledge path", "jnana yoga"],
    "karma marg": ["karma marg", "action path", "karma yoga"],
    "raaj marg": ["raaj marg", "royal path", "raja yoga"],
    "hit premanand ji": ["hit premanand ji", "shri hit premanand", "premanand ji maharaj", "premanand ji"],
    "premanand ji ke pravachan": ["premanand ji ke pravachan", "premanand discourses", "hit premanand pravachan"],
    "bhajan marg ke sawaal": ["bhajan marg ke sawaal", "bhajan marg questions", "satsang questions"],
    "child abuse": ["bachche ka shoshan", "बच्चे का शोषण", "child molestation", "बाल शोषण"],
    "betrayal": ["dhokha", "vishwasghat", "विश्वासघात", "cheating", "bevafai"],
    "homosexual": ["samlaingik", "समलैंगिक", "gay", "lesbian", "lgbt", "queer", "समलैंगिकता"],
    "homo sexual": ["homosexual", "gay", "lesbian", "समलैंगिक", "samlaingik"],
    "homo sexuals": ["homosexual", "gay", "lesbian", "समलैंगिक", "samlaingik"],
}

# NEW: Spiritual question patterns to whitelist English queries
SPIRITUAL_QUESTION_PATTERNS = [
    "how to ", "what is ", "why does ", "can i ", "how do i ",
    "how can i ", "is it ", "should i ", "why is ", "what are ",
    "how does ", "tell me about ", "explain ", "meaning of ",
    "how to control ", "how to overcome ", "how to deal with ","daughter", "father", "mother", "son", "parent", "family",
    "shree ji", "shri ji", "maharaj ji", "guru ji", "swami ji", "prabhu ji",
    "radhe radhe", "hare krishna", "jai shri ram", "jai mata di",
]